---
# Check for updates to the securedrop-admin package
- name: Check if securedrop-admin package is up to date
  hosts: localhost
  become: yes
  max_fail_percentage: 0
  any_errors_fatal: yes
  connection: local
  gather_facts: yes
  environment:
    LC_ALL: C
  roles:
    - role: update-check
