---
# Permit direct access via SSH
ssh_net_in_override: 0.0.0.0/0

# In libvirt, we want to connect over eth0, not eth1 which is used for
# inter-VM communication for OSSEC.
ssh_ip: "{{ ansible_default_ipv4.address }}"

# Make sure correct packages are used during installation
securedrop_target_distribution: "noble"

# config_path needs to be set for packaged securedrop-admin script
config_path: "/home/{{ lookup('env', 'USER') }}/.config/securedrop-admin"
